import os
from os.path import join,split,splitext

from bioscons.r_lang import sweave, stangle

vars = Variables()
env = Environment(ENV=os.environ, variables=vars)

env['BUILDERS']['sweave'] = sweave
env['BUILDERS']['stangle'] = stangle

texfile = env.sweave(source='document.Rnw')
rfile = env.stangle(source='document.Rnw')

# fails if pdflatex not in $PATH
# env.PDF(source=texfile)

