import os
from os import path
import sys
import json

import pprint

# use local (not system) version of the package
sys.path.insert(0, '../..')

from bioscons.fileutils import split_path
from bioscons.refpkg import get_vars

refpkg_path = '../../tests/testfiles/mostly_empty.refpkg'

vars = Variables()
vars.AddVariables(*get_vars(refpkg_path))

env = Environment(ENV=os.environ, variables=vars)

with open(path.join(refpkg_path, 'CONTENTS.json'), 'rU') as fobj:
    contents = json.load(fobj)

assert env.has_key('refpkg')
for label in contents['files'].keys():
    assert env.has_key(label)

