import os
from os import path
import sys

import pprint

# use local (not system) version of the package
sys.path.insert(0, '../..')

from bioscons.pplacer import align_and_place

refpkg = '../../tests/testfiles/lactobacillus2-0.3.refpkg'
qseqs = '../../tests/testfiles/short16s.fasta'

vars = Variables()
env = Environment(ENV=os.environ, variables=vars)

from bioscons.pplacer import align_and_place

env.AddMethod(align_and_place, "align_and_place")    

sto, scores, merged, placefile = env.align_and_place(
    refpkg, qseqs, outdir = '.')

sto, scores, merged, placefile = env.align_and_place(
    refpkg = refpkg,
    qseqs = qseqs,
    options = '-p --inform-prior --map-identity',
    outdir = 'place1'
    )

sto, scores, merged, placefile = env.align_and_place(
    refpkg = refpkg,
    qseqs = qseqs,
    options = '-p --inform-prior --map-identity',
    outdir = 'place2',
    nproc = 4
    )


